export default {
  self: 'xroom',
  on: 'ouvert',
  off: 'fermé',
  title: 'Besoin de configurer une salle?',
  buttons: {
    ok: 'OK',
    yes: 'Oui',
    no: 'Non',
    cancel: 'Annuler',
    retry: 'Essayer de nouveau',
    chooseWindow: 'Choisi une fenêtre',
    wholeScreen: 'Toute l'écran',
    install: 'Ajouter',
    uninstall: 'Enlever',
    send: 'Envoyer',
    close: 'Ferme',
    hide: 'Cache',
    knock: 'Toc-toc',
    allowIn: 'Laisse entrer',
    deny: 'Refuse',
    enterAnyway: 'Entre pareil',
  },
  mbox: {
    notSupported: 'Il semble que ce navigateur ne prend pas en charge XROOM ou WebRTC est désactivé. 😢',
    success: 'Opération réussie',
    failure: 'Opération échouée',
    enterRoomName: 'Entrer un nom de salle svp',
    isCamOn: 'Est-ce que votre caméra est ouverte?',
    isCamOnText: 'Veuillez vérifier que vous n'avez pas accidentellement bloqué votre caméra / micro sur ce site et appuyez sur "Réessayer".',
    isMicOn: 'Est-ce que votre microphone est ouvert?',
    isMicOnText: 'Si vous prévoyez de parler, nous avons besoin de votre autorisation de micro. Autorisez-le sur cette page et appuyez sur "Réessayer".',
    iWillOnlyWatch: 'Je veux juste regarder',
    iWillOnlyListen: 'Je veux juste écouter',
    screenSharingText: 'Le partage d'écran n'est pas autorisé. Veuillez vous assurer qu'elle n'est pas bloquée pour cette page. <br> <br> Cette fonctionnalité n'est également prise en charge que par les navigateurs modernes comme Chrome ou Firefox. ',
    cannotFile: 'Étant donné que nous ne touchons même pas vos fichiers, nous ne pouvons les livrer que lorsque les gens sont entrés. ',
    cannotMessage: 'Comme nous ne touchons même pas à vos messages, nous ne pouvons les livrer maintenant. Vous devez le faire quand les gens sont entrés. ',
    roomLockedText: 'Cette salle est barrée',
    oops: 'Désolé',
    kickedOutText: 'Vous avez été expulsé',
    areYouSure: 'Êtes vous certain?',
    restartRequiredText: 'Ce paramètre affecte trop de choses, donc un rechargement est nécessaire. C'est rapide, ne vous inquiétez pas!',
    onlySafariOnIOS: 'Avec ios juste Safari est supporté. "Merci", Apple!',
    cannotLoadPlugin: 'Plugin "%s" ne fonctionne pas sur votre navigateur',
    confirmFileSend: ' Voulez-vous envoyer ça?',
    whatIsYourName: 'Entrer votre nom',
    setVideoVolume: 'Ajuster le volume de cette vidéo',
    roomLockedTryKnockText: 'La salle est actuellement verrouillée. Vous pouvez demander la permission en "frappant" à la porte.',
    knockingFailedText: 'Échec de la tentative pour entrer',
    doYouWantToKick: 'Voulez-vous renvoyer cet utilisateur??',
    deviceChanged: 'Vous avez connecté / supprimé un nouveau périphérique d'entrée. Si cela ne fonctionne pas, choisissez-le manuellement dans les paramètres.',
    allowCameraPlz: 'Après avoir appuyé sur OK, veuillez <b> autoriser </b> xroom à utiliser votre appareil photo. <br> <br> Ne vous inquiétez pas! Vous pourrez le désactiver à nouveau avant d'entrer dans la pièce en bas du menu si vous souhaitez rester invisible. ',
    tooOldBrowser: 'Votre navigateur est trop ancien ou est produit par Microsoft. De nombreuses fonctionnalités peuvent manquer. '
    pluginsLoadFailed: 'Échec du chargement des plugins',
    protoExpired: 'Version client trop ancienne. Veuillez appuyer sur Ctrl & nbsp; + & nbsp; Maj & nbsp; + & nbsp; F5 pour recharger. Si vous voyez à nouveau ce message, veuillez vider manuellement le cache du navigateur.',
    peerError: 'Quelque chose s'est mal passé lors de l'échange de données avec vos pairs. Nous vous suggérons de recharger la page.',
    enterpriseOnly: 'Il s'agit d'une fonction réservée aux entreprises.',
    pluginSuggested: 'L'utilisateur% s vous a suggéré d'installer le plugin% s. Souhaitez-vous le faire?',
    hostRoleRequired: 'Le rôle d'hôte est requis pour cette action.',
    alreadyHosted: 'La salle est déjà hébergée. N'entrez pas dans la même pièce à partir de 2 onglets du navigateur. 😉',
    roomLockedPassword: 'La salle est actuellement verrouillée avec un mot de passe. Entrez-le ci-dessous si vous le connaissez.',
    roomDestroyed: 'La salle a été détruite. Vous serez redirigé vers la page de démarrage.',
  },
  notify: {
    slowPlugins: 'Les plugins prennent trop de temps à charger. Pensez à retirer le plus lourd.',
  },
  home: {
    nisdos: 'Nous n'utilisons pas les cookies',
    title: 'Votre salle de conférence personnelle',
    btnGo: 'Go!',
    knowMore: 'A propos de xroom',
    nameRoom: 'nom de votre salle:',
    placeholder: 'écrire ici',
    rejoinRoom: 'ou rejoindre',
  },
  wl: {
    poweredBy: 'Propulsé par ',
  },
  modes: {
    1: 'Conférence',
    2: 'Webinaire',
  },
  pre: {
    selectMode: 'Choisir un type de salle',
    checkIt: 'Vérifiez votre micro et votre coupe de cheveux',
    btnGo: 'J'entre',
    knockDenied: 'Votre demande pour entrer a été refusée. Vous ne pouvez pas assister à la rencontre. :(',
    knockRequested: 'En attente d'une autorisation. Les gens peuvent vous voir. 👀',
    noAudio: '⚠️ Aucun signal micro détecté',
    roomIsBusyWebinar: 'Un webinaire est en cours d'exécution(%s × 🙂)',
    roomIsBusyConference: 'Une conférence est en cours d'exécution (%s × 🙂)',
    sizeLimitReached: 'Cette chambre est limitée par la taille et la limite est atteinte',
  },
  videoMenu: {
    hint: 'Basculer le menu',
    expand: 'Développer',
    fullscreen: 'Plein écran',
    volume: 'Volume ±',
    restore: 'Restorer',
    kick: 'Frapper',
    mute: 'Muet',
  },
  controls: {
    ss: 'Partage d'écran %s',
    cam: 'Cam %s',
    mic: 'Mic %s',
    chat: 'Chat %s',
    exit: 'Sortie',
    destroy: 'Éliminer',
    xroom: 'Propulsé par xroom',
    settings: 'Configurations',
    plugins: 'Plugins',
    media: 'Média',
    more: 'Plus',
    letMeSpeak: 'Laissez moi parler',
  },
  reactions: {
    letMeSpeak: 'Je veux parler!',
  },
  waiting: {
    invite: 'Inviter vos confrères',
    beforeCopy: 'clique pour copier',
    afterCopy: 'Copié.  Vous pouvez partager maintenant!',
    webinar: 'Webinaire n'est pas encore décollé',
  },
  video: {
    you: 'Vous (Entrez votre nom)',
    someone: 'Quelqu'un',
    knocking: 'cogne...',
    poorNet: 'connexion faible',
  },
  chat: {
    fileSending: 'Envoie d'un ficher: ',
    fileReceived: 'Fichier reçu: ',
    inputPlaceholder: 'Tapez un message et appuyez sur Entrée ...',
    me: 'moi',
    dropMe: 'Dépose-moi!',
  },
  webinar: {
    peersCount: '%s personnes assistent présentement',
  },
  settings: {
    experimental: '*) expérimental, fonctionne de manière instable',
    showCameraWithScreen: 'Afficher la caméra pendant le partage d'écran *',
    qualityLevel: 'High quality (uses more traffic)',
    autoGetIn: 'Démarrer des chats sans aperçu',
    soundEffects: 'Effets sonores',
    noisyBackground: 'Je suis dans une place bruyante',
    rtcDebug: 'Debogue RTC',
    audioDevices: 'Sources audios',
    videoDevices: 'Sources vidéos',
    language: 'Langue',
    theme: 'Couleur du thème',
    server: 'Serveur',
  },
  plugins: {
    by: 'par',
    size: 'dimension: %s kB',
    searchPlaceholder: 'cherche...',
    source: 'Code source',
    add: {
      title: 'Ajouter une nouveau plugin',
      descr: '⚙️ Vous développez un nouveau plugin? Ajoutez-le ici au test. Il n'est pas enregistré, le rechargement de la page la supprime de la mémoire. Le manuel de l'API des plugins est disponible <a href="https://github.com/punarinta/xroom-plugins" target="_blank"> ici </a>. ',
      name: 'Quel est le nom du plugin?',
      rootUrl: 'Où est la racine du plugin?',
      loaded: 'Super!  C'est chargé!',
      loadFailed: 'Échec du chargement du plugin',
    }
  },
  feedback: {
    header: 'Oh, Désolé, juste une seconde...',
    question: 'Est-ce que tout s'est bien passé cette fois?',
    videoFroze: 'Non, la vidéo s'est figée',
    soundLagged: 'Non, son retardé',
    cantConnect: 'Non, personne ne pouvait se connecter',
    smthElse: 'Autre chose:',
    feedbackInput: 'laissez vos commentaires...',
    contactMe: 'Contactez moi s'il vous plait:',
    emailInput: 'votre courriel...',Vous manquez des appels vidéo dans Telegram? Notre <a href="//about.xroom.app/en/library/telegram-bot" target="_blank"> bot Telegram </a> est là pour vous aider.
  },
  tips: {
    prefix: 'Conseil du jour: ',
    lines: [
      'Désactiver / réactiver le son souvent? Il y a un raccourci "m" pour ça.',
      'Double-cliquez sur une vidéo à distance pour la faire en plein écran.',
      'Besoin de verrouiller votre salle? Ajoutez simplement le verrouillage de la pièce dans les plugins ci-dessous.',
      'Utilisez Slack et vous voulez gagner plus de temps? Essayez notre <a href="//about.xroom.app/en/library/slack-bot" target="_blank"> Slack bot </a>.',
      'Vous manquez des appels vidéo dans Telegram? Notre <a href="//about.xroom.app/en/library/telegram-bot" target="_blank"> bot Telegram </a> est là pour vous aider.',
      'Besoin de partager une image copiée? Ctrl + V dans le chat, nous faisons le reste.',
      'Cliquez pour changer votre nom à la fois localement et pour vos pairs.',
      'Avez-vous déjà eu besoin d'enregistrer votre écran en quelques clics? Essayez notre plugin d'enregistrement d'écran.',
      'Besoin d'esquisser pendant un appel - essayez le plugin d'esquisse. N'oubliez pas d'activer le partage d'écran.',
      'Cliquez sur votre nom ou "Vous" pour vous renommer pour tout le monde.',
    ]
  },
}
